org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.22
neo_version_range=[21.1,)
loader_version_range=[2,)

mod_id=laserio_aditionals
mod_name=LaserIO Additionals
mod_license=MIT
mod_version=1.0-SNAPSHOT
mod_group_id=com.lucasmellof
mod_authors=lucasmellof
mod_description=Additional LaserIO integrations for PneumaticCraft and Applied Energistics 2.

curseforge_project_id=1713883
